### ISSUE TITLE
Small Bug Fix

### ISSUE THREAD

**Issue by RedH11** [devmarcstorm/python-network-scanner#1]
In main on line 35, you check for whether or not _open("{}/devices.json".format(dataPath), "r")_, which looks for the file **devices.json** with an s at the end of devices, but in the error explanation thrown on line 39, you reference the need for there to be a device.json (no s in device[s] there) which means that the user would create a device.json but still have the FileNotFound Error. 

Small fix, just add an s to the error explanation. Thanks for the cool project!

**Comment by devmarcstorm** [comment]
# Thanks

Hi, **thank you** for bringing this to my attention and sorry for the late reply... *I really need to pay more attention to my notifications.* I am also happy that you like my project. Thanks again

I fixed the typo in commit ce8e4c8.
